import Head from "next/head";
import SiteText from "../components/siteText/SiteText";

const AboutUs = () => {
  return (
    <div>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SiteText
          title="Haqqımızda"
          description="Tap.az layihəsi Azərbaycanda özəl elanlar üçün universal meydança təşkil etmək məqsədi ilə yaradılıb.

      Hər bir kəs saytdan istifadə etməklə geyim və mebeldən tutmuş elektronika və avtomobilədək hər şey ala və sata bilər.
      
      Tap.az-a əsasən ayrıca fərdlər elan yerləşdirir, lakin sayt şirkət və fərdi sahibkarlar üçün də maraq kəsb edir, buna görə Tap.az-da təkcə işlənmiş deyil, eləcə də yeni məhsullar əldə etmək olar."
          color="#F3FFF8"
          height="500px"
          borderColor="#80BC96"
        />
      </main>
    </div>
  );
};

export default AboutUs;
