import Head from "next/head";
import BlogItemDetail from "../components/blog&news/BlogItemDetail";
import cardImg from "../public/assets/image/MaskGroup.png";

const Blog = () => {
  return (
    <div>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div>
            <h1>Blog</h1>
          </div>
          <div className="row align-items-center">
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
            <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-3">
              <BlogItemDetail
                img={cardImg}
                desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                title="Uşaqlar üçün oyuncaq dəsti"
                view="20"
                time="Bakı, 08-08-2021"
                href="/BlogDetail"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Blog;
