import styles from "../styles/_blogDetail.module.scss";
import Head from "next/head";
import Image from "next/image";
import blogImg from "../public/assets/image/blog.png";
import * as Icon from "react-bootstrap-icons";
import Link from "next/link";

const BlogDetail = () => {
  return (
    <div>
      <Head>
        <title>BLog Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.blogDetail}>
          <div className="myContainer">
            <div className="row ">
              <div className="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8 col-xxl-8">
                <div className={styles.blogDetailContent}>
                  <figure>
                    <Image
                      layout="responsive"
                      src={blogImg}
                      height={330}
                      objectFit="cover"
                    />
                    <div
                      className={`${styles.blogDetailView} d-flex align-items-center justify-content-between`}
                    >
                      <figcaption>08-08-2021 09:15</figcaption>
                      <figcaption className="d-flex align-items-center">
                      
                        <Icon.Eye className={styles.eye} /> 20
                      </figcaption>
                    </div>
                    <figcaption className={styles.blogTextDetail}>
                      <h1>Uşaqlar üçün oyuncaq dəsti</h1>
                      <p>
                        Eu nulla sit morbi velit aliquam id. Etiam semper nec
                        velit semper blandit mauris arcu elit. Aliquet quis
                        dictumst cras fermentum sit interdum non metus. Eget
                        odio scelerisque consequat dictumst tellus. Lorem ipsum
                        dolor sit amet, consectetur adipiscing elit. Condimentum
                        morbi quis posuere rutrum id urna in etiam. Sit varius
                        proin ac duis turpis mollis in ultrices. Accumsan
                        blandit ac sit vestibulum donec tincidunt cursus. Eu
                        nulla sit morbi velit aliquam id. Etiam semper nec velit
                        semper blandit mauris arcu elit. Aliquet quis dictumst
                        cras fermentum sit interdum non metus. Eget odio
                        scelerisque consequat dictumst tellus. Lorem ipsum dolor
                        sit amet, consectetur adipiscing elit. Condimentum morbi
                        quis posuere rutrum id urna in etiam. Sit varius proin
                        ac duis turpis mollis in ultrices. Accumsan blandit ac
                        sit vestibulum donec tincidunt cursus.
                      </p>
                    </figcaption>
                  </figure>
                </div>
              </div>
              <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 col-xxl-4">
                <div className={styles.otherBlog}>
                  <div className={styles.otherBlogHead}>
                    <h3>Son xəbərlər</h3>
                  </div>
                  <div className={styles.otherBlogContent}>
                    <div className="d-flex align-items-center">
                      <div className="leftImg">
                        <Image width={110} height={110} src={blogImg} />
                      </div>
                      <div className={styles.otherBlogContentText}>
                      <Link href="/BlogDetail"><a>  <h5>Uşaqlar üçün oyuncaq dəsti</h5></a></Link>
                        <div className={styles.otherBlogContentDate}>
                          <div className="d-flex justify-content-between align-items-center">
                            <p>08-08-2021 09:15</p>
                            <p className="d-flex align-items-center">
                              <Icon.Eye className={styles.eye} /> 20
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.otherBlogContent}>
                    <div className="d-flex align-items-center">
                      <div className="leftImg">
                        <Image width={110} height={110} src={blogImg} />
                      </div>
                      <div className={styles.otherBlogContentText}>
                      <Link href="/BlogDetail"><a>  <h5>Uşaqlar üçün oyuncaq dəsti</h5></a></Link>
                        <div className={styles.otherBlogContentDate}>
                          <div className="d-flex justify-content-between align-items-center">
                            <p>08-08-2021 09:15</p>
                            <p className="d-flex align-items-center">
                              <Icon.Eye className={styles.eye} /> 20
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.otherBlogContent}>
                  <div className="d-flex align-items-center">
                    <div className="leftImg">
                      <Image width={110} height={110} src={blogImg} />
                    </div>
                    <div className={styles.otherBlogContentText}>
                    <Link href="/BlogDetail"><a>  <h5>Uşaqlar üçün oyuncaq dəsti</h5></a></Link>
                      <div className={styles.otherBlogContentDate}>
                        <div className="d-flex justify-content-between align-items-center">
                          <p>08-08-2021 09:15</p>
                          <p className="d-flex align-items-center">
                            <Icon.Eye className={styles.eye} /> 20
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={styles.otherBlogContent}>
                <div className="d-flex align-items-center">
                  <div className="leftImg">
                    <Image width={110} height={110} src={blogImg} />
                  </div>
                  <div className={styles.otherBlogContentText}>
                  <Link href="/BlogDetail"><a>  <h5>Uşaqlar üçün oyuncaq dəsti</h5></a></Link>
                    <div className={styles.otherBlogContentDate}>
                      <div className="d-flex justify-content-between align-items-center">
                        <p>08-08-2021 09:15</p>
                        <p className="d-flex align-items-center">
                          <Icon.Eye className={styles.eye} /> 20
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default BlogDetail;
