import { Typography } from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/_brands.module.scss";

const Brands = () => {
  return (
    <div>
      <Head>
        <title>Brands Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.brandsPage}>
          <div className="container">
            <div className={styles.brandHead}>
              <h2>Brendlər</h2>
            </div>
            <div className={styles.brandWordList}>
              <div className="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <ul className="d-flex flex-wrap align-items-center">
                  <li>
                    <Link href="/JobSeeker">
                      <a>A</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/Offer">
                      <a>B</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/Shop">
                      <a>C</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/News">
                      <a>Ç</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/Blog">
                      <a>D</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/BlogDetail">
                      <a>E</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ProductDetail">
                      <a>Ə</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/Contact">
                      <a>F</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/WishList">
                      <a>G</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/myAccount">
                      <a>H</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ssd">
                      <a>X</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/aaa">
                      <a>İ</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/fff">
                      <a>J</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/rrr">
                      <a>K</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ggg">
                      <a>Q</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ttt">
                      <a>L</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/rrr">
                      <a>M</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/azaza">
                      <a>N</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/jjj">
                      <a>O</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/lll">
                      <a>Ö</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ddds">
                      <a>P</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/tyty">
                      <a>R</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/wewe">
                      <a>S</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/tgtgdf">
                      <a>Ş</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/zzzz">
                      <a>T</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/uuu">
                      <a>U</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/ooo">
                      <a>Ü</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/klo">
                      <a>V</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/hgr">
                      <a>Y</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/hdf">
                      <a>Z</a>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className={styles.brandNameList}>
              <span>
                A
                <ul>
                  <li>
                    <Link href="/">
                      <a>Andrea Turchi</a>
                    </Link>
                  </li>
                </ul>
              </span>
              <span>
                B
                <ul>
                  <li>
                    <Link href="/AboutUs">
                      <a>Brunello Cucinelli</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/login">
                      <a>Black Coral</a>
                    </Link>
                  </li>
                </ul>
              </span>
              <span>
                C
                <ul>
                  <li>
                    <Link href="/register">
                      <a>Cortigiani</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/JobsDetail">
                      <a>Celine</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/PlaceDetail">
                      <a>Cambiaghi</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/SearchResult">
                      <a>Chiara Ferragni</a>
                    </Link>
                  </li>
                </ul>
              </span>
              <span>
                Ç
                <ul>
                  <li>
                    <Link href="/SiteAds">
                      <a>Brunello Cucinelli</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/UserAgreement">
                      <a>Black Coral</a>
                    </Link>
                  </li>
                </ul>
              </span>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Brands;
