import Head from "next/head";
import styles from "../styles/_consult.module.scss";

const consult = () => {
  return (
    <div>
      <Head>
        <title>consult Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.consultPage}>
          <div className="myContainer">
            <div className={styles.consultHead}>
              <h2>Onlayn qeydiyyat</h2>
            </div>
            <div className={styles.consultForm}>
              <form>
                <div className="row align-items-center">
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="text" placeholder="Adınız və soyadınız" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="tel" placeholder="Əlaqə nömrəsi" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="datetime" placeholder="Doğum tarixi" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="email" placeholder="E-mail" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="datetime" placeholder="Qəbul tarixi" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-5 col-lg-5 col-xl-5 col-xxl-5`}>
                    <input type="datetime" placeholder="Saat" />
                  </div>
                  <div className={`${styles.inputBox} col-12 col-sm-12 col-md-11 col-lg-11 col-xl-11 col-xxl-11`}>
                    <textarea
                      cols="30"
                      rows="10"
                      placeholder="Xüsusi qeydlər"
                    ></textarea>
                  </div>
                  <div className={`${styles.inputBox} ${styles.sendBtn} col-12 col-sm-12 col-md-11 col-lg-5 col-xl-4 col-xxl-4`}>
                   <input  type="submit" value="Göndər" />
                </div>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default consult;
