import Head from "next/head";
import styles from "../styles/_createAds.module.scss";
import InputLabel from "@mui/material/InputLabel";
import MenuItem from "@mui/material/MenuItem";
import ListSubheader from "@mui/material/ListSubheader";
import FormControl from "@mui/material/FormControl";
import Select from "@mui/material/Select";

const AboutUs = () => {
  return (
    <div>
      <Head>
        <title>Create ADS page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.createAdsPage}>
          <div className="myContainer">
            <div className={styles.adsHead}>
              <h2>Elan yerləşdir</h2>
            </div>
            <form className={styles.formAds}>
              <div className="row">
              <div className="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className={styles.mainContent}>
                  <div className={styles.mainContentHead}>
                    <h5>Əsas məlumatlar</h5>
                    <div>
                      <FormControl className={styles.categoryList} sx={{ m: 1, minWidth: 220 }}>
                        <InputLabel htmlFor="grouped-native-select">
                        Kateqoriyanı seçin
                        </InputLabel>
                        <Select
                          native
                          defaultValue=""
                          id="grouped-native-select"
                          label="Kateqoriyanı seçin"
                        >
                          
                          <optgroup label="Category 1">
                            <option value={1}>Option 1</option>
                            <option value={2}>Option 2</option>
                          </optgroup>
                          <optgroup label="Category 2">
                            <option value={3}>Option 3</option>
                            <option value={4}>Option 4</option>
                          </optgroup>
                        </Select>
                      </FormControl>
                   
                    </div>
                  </div>
                </div>
              </div>
              </div>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
};

export default AboutUs;
