import { useEffect, useState } from "react";

import Head from "next/head";
import styles from "../styles/_createAds.module.scss";
import * as Icon from "react-icons/bs";
import $ from "jquery";
import Image from "next/image";
import catImg from "../public/assets/image/catImg.png";
import Link from "next/link";

const createAds = () => {
  const [activeField, setActiveField] = useState(false);
  useEffect(() => {
    let fieldBox = document.querySelectorAll(`.${styles.fieldName}`);
    let catImg = document.querySelectorAll(`.${styles.categoryBox}`)
    console.log(catImg);
    for (let i = 0; i < fieldBox.length; i++) {
      fieldBox[i].onclick = () => {
        setActiveField(activeField ? false : true);
        $(`.${styles.fieldBoxContent}`).stop().slideToggle();
      };
    }
    for (let j = 0; j < catImg.length; j++) {
     catImg[j].onclick = () => {
      catImg[j].classList.toggle(`${styles.activeCat}`)
     }
     
    }
  });
  return (
    <div>
      <Head>
        <title>Create ADS page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.createAdsPage}>
          <div className="myContainer">
            <div className={styles.adsHead}>
              <h2>Elan yerləşdir</h2>
            </div>
            <form className={styles.formAds}>
              <div className="row">
                <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 col-xxl-3">
                  <div className={styles.formHead}>
                    <h5>Əsas məlumatlar</h5>
                  </div>
                  <label htmlFor="">Kateqoriyanı seçin</label>
                  <div className={styles.fieldBox}>
                    <div className={styles.fieldName}>
                      <div className="d-flex align-items-center justify-content-between">
                        <span>Siyahıdan seçin</span>
                        {activeField ? (
                          <Icon.BsChevronUp />
                        ) : (
                          <Icon.BsChevronDown />
                        )}
                      </div>
                    </div>
                    <div className={styles.fieldBoxContent}>
                      <div className="row">
                        <div className="col-4 col-sm-3  col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <input type="text" hidden value={"87"} />
                            <figure>
                              <Image className={styles.catImg} width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                        <div className="col-4 col-sm-3 col-md-3 col-lg-4 col-xl-4 col-xxl-3">
                          <div className={styles.categoryBox}>
                            <figure>
                              <Image width={80} height={80} src={catImg} />
                              <figcaption>
                                <h6>Oyuncaq</h6>
                              </figcaption>
                            </figure>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
};

export default createAds;
