import Head from "next/head";
import CategoryItem from "../components/categoryItem/CategoryItem";
import styles from "../styles/Home.module.scss";
import Image from "next/image";
import chick from "../public/assets/image/cuceimage21.png";
import ScrollBottom from "../components/scrollBottom/ScrollBottom";
import AdvertItem from "../components/advertSection/AdvertItem";
import BlogItemDetail from "../components/blog&news/BlogItemDetail";
import cardImg from "../public/assets/image/MaskGroup.png";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import { Pagination, Autoplay } from "swiper";
import BlogItemHead from "../components/blog&news/BlogItemHead";
import { useRouter } from "next/router";
import AdvertCard from "../components/advertSection/AdvertCard";
import diamond from "../public/assets/image/diamond1.png";
import crystal from "../public/assets/image/jam_crown-f.png";
import { connect } from "react-redux";
import imgOne from "../public/assets/image/proDetail1.jpg";
import imgTwo from "../public/assets/image/proDetail2.jpg";

export function Home({ products }) {
  const { locale } = useRouter();

  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.categorySection}>
          <div className="container">
            <div className="row align-items-center">
              <div className={styles.categoryList}>
                <div className="row align-items-center">
                  <div className="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 col-xxl-6">
                    <div className="row align-items-center">
                      <CategoryItem
                        href="/Product"
                        txtColor="#DC7E69"
                        bg="#FFDCD2"
                        title="Oyuncaq"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#5EB57E"
                        bg="#C8F1D7"
                        title="Geyim"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#63A7C6"
                        bg="#CDEEFC"
                        title="Mebel"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#8D6D5C"
                        bg="#E8DED9"
                        title="Mağazalar"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#44ADA1"
                        bg="#ADFFF5"
                        title="Sağlamlıq"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#E3B600"
                        bg="#FFF3B8"
                        title="Təhsil"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#6871B6"
                        bg="#C0C2E0"
                        title="İş axtaranlar"
                      />
                      <CategoryItem
                        href="/Product"
                        txtColor="#A96263"
                        bg="#FFDADA"
                        title="Əyləncə"
                      />
                    </div>
                  </div>
                  <div className="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 col-xxl-6">
                    <div className={styles.rightImg}>
                      <Image objectFit="cover" src={chick} />
                    </div>
                  </div>
                </div>
                <div className={styles.scrollBottom}>
                  <div className="my-5 d-flex justify-content-center align-items-center">
                    <ScrollBottom />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.advertSection}>
          <div className="container">
            <AdvertItem
              titleText="VİP elanlar"
              textColor="#5EB57E"
              buttonText="Daha çox"
              cardItem={products
                .filter((p) => p.locale === locale && p.isVip === true)
                .map((fakeApi, i) => {
                  return (
                    <div key={i} className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                      <AdvertCard
                        id={fakeApi.id}
                        
                        photoUrl={
                          "https://www.dekorstore.net/wp-content/uploads/2019/06/dogtas-cocuk-odasi-takimi-modelleri-1200x800.jpg"
                        }
                        title={fakeApi.productName}
                        price={fakeApi.price}
                        ticket={fakeApi.sellStatus}
                        iconOne={diamond}
                        iconTwo={crystal}
                        date={fakeApi.dateAndCity}
                        href="/ProductDetail"
                        isAddWish={false}
                        isOffer={false}
                      />
                    </div>
                  );
                })}
            />
            <AdvertItem
              titleText="Premium elanlar"
              textColor="#C87C69"
              buttonText="Daha çox"
              cardItem={products
                .filter((p) => p.locale === locale && p.isVip === true)
                .map((fakeApi, i) => {
                  return (
                    <div  key={i} className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                      <AdvertCard
                       
                        id={fakeApi.id}
                        photoUrl={imgOne}
                        title={fakeApi.productName}
                        price={fakeApi.price}
                        ticket={fakeApi.sellStatus}
                        iconOne={diamond}
                        iconTwo={crystal}
                        date={fakeApi.dateAndCity}
                        href="/ProductDetail"
                        isAddWish={false}
                        isOffer={false}
                      />
                    </div>
                  );
                })}
            />
            <AdvertItem
              titleText="Son elanlar"
              textColor="#6871B6"
              buttonText="Daha çox"
              cardItem={products
                .filter((p) => p.locale === locale && p.isVip === true)
                .map((fakeApi, i) => {
                  return (
                    <div  key={i} className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                      <AdvertCard
                        id={fakeApi.id}
                       
                        photoUrl={imgTwo}
                        title={fakeApi.productName}
                        price={fakeApi.price}
                        ticket={fakeApi.sellStatus}
                        iconOne={diamond}
                        iconTwo={crystal}
                        date={fakeApi.dateAndCity}
                        href="/ProductDetail"
                        isAddWish={false}
                        isOffer={false}
                      />
                    </div>
                  );
                })}
            />
          </div>
        </section>
        <section className={styles.blog}>
          <div className="container">
            <BlogItemHead link="/News" title="Xəbərlər" color="#A96263" />
            <div className={styles.blogItem}>
              <Swiper
                loop={true}
                slidesPerView={"auto"}
                slidesPerGroup={1}
                spaceBetween={30}
                breakpoints={{
                  280: {
                    slidesPerView: 1,
                  },

                  768: {
                    slidesPerView: 2,
                  },
                  1024: {
                    slidesPerView: 3,
                  },
                }}
                autoplay={{
                  delay: 3000,
                }}
                modules={[Pagination, Autoplay]}
                className="mySwiper"
              >
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
              </Swiper>
            </div>
            <BlogItemHead title="Bloq" link="/Blog" color="#63A7C6" />
            <div className={styles.blogItem}>
              <Swiper
                loop={true}
                slidesPerView={"auto"}
                slidesPerGroup={1}
                spaceBetween={30}
                breakpoints={{
                  280: {
                    slidesPerView: 1,
                  },

                  550: {
                    slidesPerView: 2,
                  },
                  1024: {
                    slidesPerView: 3,
                  },
                }}
                modules={[Pagination, Autoplay]}
                className="mySwiper"
              >
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
                <SwiperSlide>
                  <BlogItemDetail
                    img={cardImg}
                    desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dignissim posuere ac egestas ac ..."
                    title="Uşaqlar üçün oyuncaq dəsti"
                    view="20"
                    time="Bakı, 08-08-2021"
                    href="/BlogDetail"
                  />
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

const mapStateToProps = (state) => {
  return {
    products: state.cart.products,
  };
};

export default connect(mapStateToProps)(Home);
