import Head from "next/head";
import Image from "next/image";
import styles from "../styles/_jobsDetail.module.scss";
import doctorImg from "../public/assets/image/doctor.jpg";
import OutlineButton from "../components/button/Button";
import Link from "next/link";

const JobsDetail = () => {
  return (
    <div>
      <Head>
        <title>Doctor Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.jobsDetail}>
          <div className="myContainer">
            <div className="row">
              <div className="col-12 col-sm-12 col-md-12 col-lg-5 col-xl-5 col-xxl-5">
                <figure className={styles.detailContact}>
                  <Image
                    layout="responsive"
                    height={200}
                    width={300}
                    objectFit="cover"
                    src={doctorImg}
                    className={styles.personImg}
                  />
                  <figcaption className={styles.fullName}>
                    <h2>Aygun Memmedova</h2>
                    <p>Pediatr</p>
                  </figcaption>
                  <figcaption className={styles.contactInfo}>
                    <ul>
                      <li>
                        <span>İşlədiyi yer:</span> Sağlam Ailə
                      </li>
                      <li>
                        <span>İş günləri:</span> Bazar ertəsi - Şənbə
                        09:00-20:00
                      </li>
                      <li>
                        <span>Telefon:</span> (+994 50) 345 67 89
                      </li>
                      <li>
                        <span>Email:</span> a.terlan@saglamaile.az
                      </li>
                    </ul>
                  </figcaption>
                  <figcaption className={styles.onlineRegisterBtn}>
                    <Link href="/consult"><a>Onlayn qeydiyyat</a></Link>
                  </figcaption>
                  <figcaption className={styles.advertButton}>
                    <OutlineButton
                      buttonContent="İrəli çək"
                      buttonBorder="1px solid #A96263"
                    />
                    <OutlineButton
                      buttonContent="VİP et"
                      buttonBorder="1px solid #80BC96"
                    />
                    <OutlineButton
                      buttonContent="Premium et"
                      buttonBorder="1px solid #FF8B6A"
                    />
                  </figcaption>
                </figure>
              </div>
              <div className="col-12 col-sm-12 col-md-12 col-lg-7 col-xl-7 col-xxl-7">
                <div className={styles.jobsContent}>
                 <div className={styles.headText}>
                  <h4>Təhsil</h4>
                 </div>
                 <div className={styles.jobsText}>
                  <ul>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                  <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>

                  </ul>
                 </div>
                </div>
                <div className={styles.jobsContent}>
                <div className={styles.headText}>
                 <h4>İş təcrübəsi</h4>
                </div>
                <div className={styles.jobsText}>
                 <ul>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                 <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo faucibus etiam ut</li>
                

                 </ul>
                </div>
               </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default JobsDetail;
