import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import AccountParameter from "../components/accountSetting/AccountParameter";
import ChangePassword from "../components/accountSetting/ChangePassword";
import MyAdvert from "../components/accountSetting/MyAdvert";
import MyCV from "../components/accountSetting/MyCV";
import MyFavorite from "../components/accountSetting/MyFavorite";
import ServiceList from "../components/accountSetting/ServiceList";
import styles from "../styles/_myAccount.module.scss";

const myAccount = () => {
  return (
    <div>
      <Head>
        <title>My Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.myAccountPage}>
          <div className="container">
            <div className={styles.accountHead}>
              <h2>Mənim profilim</h2>
            </div>
            <div className="row">
              <div className="col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 col-xxl-3">
                <ServiceList
                  listDetailProp={`._myAccount_settingItem__xv9ok`}
                />
              </div>
              <div
                className={`${styles.settingItem}  col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9`}
              >
                <AccountParameter />
              </div>
              <div
                className={`${styles.settingItem} col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9`}
              >
              <MyCV />
              </div>
              <div
                className={`${styles.settingItem} col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9`}
              >
              <MyAdvert/>
           
              </div>
              <div
                className={`${styles.settingItem} col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9`}
              >
                <MyFavorite/>
              </div>
              <div
                className={`${styles.settingItem} col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9 col-xxl-9`}
              >
                <ChangePassword />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default myAccount;
