import styles from "../styles/placeDetail.module.scss";
import Head from "next/head";
import Link from "next/link";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
// import required modules
import { FreeMode, Thumbs, Autoplay } from "swiper";
import shareIco from "../public/assets/image/share.png";
import wishIco from "../public/assets/image/heart.png";
import Image from "next/image";
import Box from "@mui/material/Box";
import Rating from "@mui/material/Rating";
import { useState } from "react";
import OutlineButton from "../components/button/Button";
import Accordion from '@mui/material/Accordion';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Typography from '@mui/material/Typography';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import * as Icon from "react-bootstrap-icons";

const PlaceDetail = () => {
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  const [value, setValue] = useState(2);
  const [expanded, setExpanded] = useState(false);
  const handleChange = (panel) => (event, isExpanded) => {
    setExpanded(isExpanded ? panel : false);
  };
  return (
    <div>
      <Head>
        <title>Place Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.placeDetail}>
          <div className="container">
            <div className={`${styles.headText}`}>
              <ul className="d-flex align-items-center ">
                <li>
                  <Link href="/">
                    <a>Ana səhifə /</a>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <a>Geyim /</a>
                  </Link>
                </li>
                <li>
                  <Link href="/ProductDetail">
                    <a>Körpə /</a>
                  </Link>
                </li>{" "}
                <li>
                  <Link href="/ProductDetail">
                    <a className={styles.activePage}>Uşaq dəsti</a>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="row ">
              <div className="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
                <div className={styles.leftTop}>
                  <div className={styles.sliderDetail}>
                    <Swiper
                      
                      spaceBetween={10}
                      slidesPerView="auto"
                      thumbs={{ swiper: thumbsSwiper }}
                      modules={[FreeMode, Thumbs, Autoplay]}
                      autoplay={{
                        delay: 3000,
                      }}
                      className="productDetailSlider2"
                    >
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImg}
                          src="https://img.vivense.com/1920x1280/images/26edcc78e79e4bbf8de038c7efdcddb1.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImg}
                          src="https://www.bebekindirim.com/3352-large_default/ottoman-90x190-cocuk-yavrulu-yatak.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                      <img
                        className={styles.detailSliderImg}
                        src="https://st.myideasoft.com/shop/du/83/myassets/products/849/20200120-141449.jpg?revision=1587825956"
                      />
                    </SwiperSlide>
                    </Swiper>
                    <Swiper
                      style={{
                        marginTop: "20px",
                      }}
                      onSwiper={setThumbsSwiper}
                      autoplay={{
                        delay: 3000,
                      }}
                      
                      spaceBetween={10}
                      slidesPerView={3}
                      freeMode={true}
                      watchSlidesProgress={true}
                      modules={[FreeMode, Thumbs, Autoplay]}
                      className="productDetailSlider"
                    >
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImgBottom}
                          src="https://img.vivense.com/1920x1280/images/26edcc78e79e4bbf8de038c7efdcddb1.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImgBottom}
                          src="https://www.bebekindirim.com/3352-large_default/ottoman-90x190-cocuk-yavrulu-yatak.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                      <img
                        className={styles.detailSliderImgBottom}
                        src="https://st.myideasoft.com/shop/du/83/myassets/products/849/20200120-141449.jpg?revision=1587825956"
                      />
                    </SwiperSlide>
                    </Swiper>
                  </div>
                  <div className={styles.promote}>
                    <div className="d-flex align-items-center">
                      <OutlineButton
                        buttonContent="İrəli çək"
                        buttonBorder="1px solid #A96263"
                      />
                      <OutlineButton
                      buttonContent="VİP et"
                      buttonBorder="1px solid #80BC96"
                    />
                    <OutlineButton
                    buttonContent="Premium et"
                    buttonBorder="1px solid #FF8B6A"
                  />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
                <div className={styles.rightTop}>
                  <div className={styles.headText}>
                    <div className="d-flex align-items-start justify-content-between">
                      <div className={`${styles.productName}`}>
                        <h1>Uşaq mebel Kombinezon LC Waikiki</h1>
                        <Box
                          sx={{
                            "& > legend": { mt: 2 },
                          }}
                        >
                          <Rating
                            name="simple-controlled"
                            value={value}
                            onChange={(event, newValue) => {
                              setValue(newValue);
                            }}
                          />
                        </Box>
                      </div>
                      <div className={styles.share}>
                        <div className="d-flex align-items-center">
                          <Image className={styles.shareIco} src={shareIco} />
                          <Image className={styles.wishIco} src={wishIco} />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.contactInfo}>
                     <h5>Əlaqə məlumatları </h5>
                     <ul>
                     <li><Icon.GeoAltFill className={styles.ico} /> Bakı, Nərimanov rayonu, Yaşar Hüseynov küç, 47</li>
                     <li><Icon.TelephoneFill className={styles.ico} /> (+99412) 564-12-33</li>
                     <li><Icon.EnvelopeFill className={styles.ico} />buta@butabagca.az</li>
                     <li><Icon.Globe className={styles.ico} />www.butabagca.az</li>
                     </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.placeDescription}>
            <Accordion expanded={expanded === 'panel1'} onChange={handleChange('panel1')}>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel1bh-content"
              id="panel1bh-header"
            >
              <Typography className={styles.accText} sx={{ width: '33%', flexShrink: 0 }}>
              Buta Uşaq Bağçası haqqında
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
              Uşaq həftənin 6 günü 8:00 – dan 20:00 – dək yaşına uyğun olaraq qruplarda təlim – tərbiyə prosesinə cəlb olunur. Bağçada 5 dəfə qidalanır və 5 dəfədən çox müxtəlif məktəbə hazırlıq, idrak, mədəni – estetik, nitq, fiziki və sosial-emosional inkişaf etdirici və xarici dil proqramlarına uyğun məşğələlərə qoşulur və müxtəlif əyləncə və istirahət xarakterli tədbirlərdə iştirak edir.
              Bağçalarımızın əsas məqsədi uşaqların fiziki və psixoloji, həmçinin intelektual inkişafını təmin edəcək tədris proqramlarını tətbiq etmək, sağlam və intelektual gələcək nəsil formalaşdırmaqdır.
              Biz “Xoşbəxt uşaq hər zaman uğur əldə edəcək” prinsipinə inanaraq, “Övladınız Hər Şeyin Ən Yaxşısına Layiqdir” siyasətini fəaliyyətində tətbiq edərək, uşaqlara özlərini tanımaq və ifadə etmək imkanı yaradırıq.
              Uşaq Bağçasında tədris qrupları 2 dildə – rus və azərbaycan dilində təşkil olunur və 2 yaşdan 6 yaşa qədər dövrü əhatə edir. Məşğələlər 20 nəfərlik qruplarda keçirilir. Qruplarda uşaqlarla işi tərbiyəçi, müəllimə və dayə həyata keçirir.
              </Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion expanded={expanded === 'panel2'} onChange={handleChange('panel2')}>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel2bh-content"
              id="panel2bh-header"
            >
              <Typography className={styles.accText} sx={{ width: '33%', flexShrink: 0 }}>Niyə Buta Uşaq Bağçası</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
              Uşaq həftənin 6 günü 8:00 – dan 20:00 – dək yaşına uyğun olaraq qruplarda təlim – tərbiyə prosesinə cəlb olunur. Bağçada 5 dəfə qidalanır və 5 dəfədən çox müxtəlif məktəbə hazırlıq, idrak, mədəni – estetik, nitq, fiziki və sosial-emosional inkişaf etdirici və xarici dil proqramlarına uyğun məşğələlərə qoşulur və müxtəlif əyləncə və istirahət xarakterli tədbirlərdə iştirak edir.
              Bağçalarımızın əsas məqsədi uşaqların fiziki və psixoloji, həmçinin intelektual inkişafını təmin edəcək tədris proqramlarını tətbiq etmək, sağlam və intelektual gələcək nəsil formalaşdırmaqdır.
              Biz “Xoşbəxt uşaq hər zaman uğur əldə edəcək” prinsipinə inanaraq, “Övladınız Hər Şeyin Ən Yaxşısına Layiqdir” siyasətini fəaliyyətində tətbiq edərək, uşaqlara özlərini tanımaq və ifadə etmək imkanı yaradırıq.
              Uşaq Bağçasında tədris qrupları 2 dildə – rus və azərbaycan dilində təşkil olunur və 2 yaşdan 6 yaşa qədər dövrü əhatə edir. Məşğələlər 20 nəfərlik qruplarda keçirilir. Qruplarda uşaqlarla işi tərbiyəçi, müəllimə və dayə həyata keçirir.
              </Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion expanded={expanded === 'panel3'} onChange={handleChange('panel3')}>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel3bh-content"
              id="panel3bh-header"
            >
              <Typography className={styles.accText} sx={{ width: '33%', flexShrink: 0 }}>
              Proqrama daxil olan məşğələlər
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
              Uşaq həftənin 6 günü 8:00 – dan 20:00 – dək yaşına uyğun olaraq qruplarda təlim – tərbiyə prosesinə cəlb olunur. Bağçada 5 dəfə qidalanır və 5 dəfədən çox müxtəlif məktəbə hazırlıq, idrak, mədəni – estetik, nitq, fiziki və sosial-emosional inkişaf etdirici və xarici dil proqramlarına uyğun məşğələlərə qoşulur və müxtəlif əyləncə və istirahət xarakterli tədbirlərdə iştirak edir.
              Bağçalarımızın əsas məqsədi uşaqların fiziki və psixoloji, həmçinin intelektual inkişafını təmin edəcək tədris proqramlarını tətbiq etmək, sağlam və intelektual gələcək nəsil formalaşdırmaqdır.
              Biz “Xoşbəxt uşaq hər zaman uğur əldə edəcək” prinsipinə inanaraq, “Övladınız Hər Şeyin Ən Yaxşısına Layiqdir” siyasətini fəaliyyətində tətbiq edərək, uşaqlara özlərini tanımaq və ifadə etmək imkanı yaradırıq.
              Uşaq Bağçasında tədris qrupları 2 dildə – rus və azərbaycan dilində təşkil olunur və 2 yaşdan 6 yaşa qədər dövrü əhatə edir. Məşğələlər 20 nəfərlik qruplarda keçirilir. Qruplarda uşaqlarla işi tərbiyəçi, müəllimə və dayə həyata keçirir.
              </Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion expanded={expanded === 'panel4'} onChange={handleChange('panel4')}>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel4bh-content"
              id="panel4bh-header"
            >
              <Typography className={styles.accText} sx={{ width: '33%', flexShrink: 0 }}>Əlavə xidmətlər və kurslar</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
              Uşaq həftənin 6 günü 8:00 – dan 20:00 – dək yaşına uyğun olaraq qruplarda təlim – tərbiyə prosesinə cəlb olunur. Bağçada 5 dəfə qidalanır və 5 dəfədən çox müxtəlif məktəbə hazırlıq, idrak, mədəni – estetik, nitq, fiziki və sosial-emosional inkişaf etdirici və xarici dil proqramlarına uyğun məşğələlərə qoşulur və müxtəlif əyləncə və istirahət xarakterli tədbirlərdə iştirak edir.
              Bağçalarımızın əsas məqsədi uşaqların fiziki və psixoloji, həmçinin intelektual inkişafını təmin edəcək tədris proqramlarını tətbiq etmək, sağlam və intelektual gələcək nəsil formalaşdırmaqdır.
              Biz “Xoşbəxt uşaq hər zaman uğur əldə edəcək” prinsipinə inanaraq, “Övladınız Hər Şeyin Ən Yaxşısına Layiqdir” siyasətini fəaliyyətində tətbiq edərək, uşaqlara özlərini tanımaq və ifadə etmək imkanı yaradırıq.
              Uşaq Bağçasında tədris qrupları 2 dildə – rus və azərbaycan dilində təşkil olunur və 2 yaşdan 6 yaşa qədər dövrü əhatə edir. Məşğələlər 20 nəfərlik qruplarda keçirilir. Qruplarda uşaqlarla işi tərbiyəçi, müəllimə və dayə həyata keçirir.
              </Typography>
            </AccordionDetails>
          </Accordion>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};



export default PlaceDetail;
