import styles from "../styles/productDetail.module.scss";
import Head from "next/head";
import Link from "next/link";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
// import required modules
import { FreeMode, Thumbs, Autoplay } from "swiper";
import shareIco from "../public/assets/image/share.png";
import wishIco from "../public/assets/image/heart.png";
import Image from "next/image";
import Box from "@mui/material/Box";
import Rating from "@mui/material/Rating";
import { useState } from "react";
import Tab from "@mui/material/Tab";
import TabContext from "@mui/lab/TabContext";
import TabList from "@mui/lab/TabList";
import TabPanel from "@mui/lab/TabPanel";
import Disqus from "disqus-react";
import OutlineButton from "../components/button/Button";
import AdvertPerson from "../components/advertPersonContent/AdvertPerson";
import AdvertCard from "../components/advertSection/AdvertCard";
import diamond from "../public/assets/image/diamond1.png";
import crystal from "../public/assets/image/jam_crown-f.png";
import {connect} from 'react-redux'
import AdvertItem from "../components/advertSection/AdvertItem";
import { useRouter } from "next/router";
import cardImg from "../public/assets/image/MaskGroup.png";

import imgThree from '../public/assets/image/proDetail3.jpg'



const ProductDetail = ({products}) => {
  const { locale } = useRouter();
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  const [value, setValue] = useState(2);
  const [valueTab, setValueTab] = useState("1");
  const handleChange = (event, newValue) => {
    setValueTab(newValue);
  };
  const disqusShortname = "cucelerimaz";
  const disqusConfig = {
    url: "http://localhost:3000/",
    identifier: "dsq-count-scr",
    title: "Title of Your Article",
  };
  return (
    <div>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={styles.productDetail}>
          <div className="container">
            <div className={`${styles.headText}`}>
              <ul className="d-flex align-items-center ">
                <li>
                  <Link href="/">
                    <a>Ana səhifə /</a>
                  </Link>
                </li>
                <li>
                  <Link href="/">
                    <a>Geyim /</a>
                  </Link>
                </li>
                <li>
                  <Link href="/ProductDetail">
                    <a>Körpə /</a>
                  </Link>
                </li>{" "}
                <li>
                  <Link href="/ProductDetail">
                    <a className={styles.activePage}>Uşaq dəsti</a>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="row ">
              <div className="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
                <div className={styles.leftTop}>
                  <div className={styles.sliderDetail}>
                    <Swiper
                      
                      spaceBetween={10}
                      slidesPerView="auto"
                      thumbs={{ swiper: thumbsSwiper }}
                      modules={[FreeMode, Thumbs, Autoplay]}
                      autoplay={{
                        delay: 3000,
                      }}
                      className="productDetailSlider2"
                    >
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImg}
                          src="https://img.vivense.com/1920x1280/images/26edcc78e79e4bbf8de038c7efdcddb1.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImg}
                          src="https://www.bebekindirim.com/3352-large_default/ottoman-90x190-cocuk-yavrulu-yatak.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                      <img
                        className={styles.detailSliderImg}
                        src="https://st.myideasoft.com/shop/du/83/myassets/products/849/20200120-141449.jpg?revision=1587825956"
                      />
                    </SwiperSlide>
                    </Swiper>
                    <Swiper
                      style={{
                        marginTop: "20px",
                      }}
                      onSwiper={setThumbsSwiper}
                      autoplay={{
                        delay: 3000,
                      }}
                      
                      spaceBetween={10}
                      slidesPerView={3}
                      freeMode={true}
                      watchSlidesProgress={true}
                      modules={[FreeMode, Thumbs, Autoplay]}
                      className="productDetailSlider"
                    >
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImgBottom}
                          src="https://img.vivense.com/1920x1280/images/26edcc78e79e4bbf8de038c7efdcddb1.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                        <img
                          className={styles.detailSliderImgBottom}
                          src="https://www.bebekindirim.com/3352-large_default/ottoman-90x190-cocuk-yavrulu-yatak.jpg"
                        />
                      </SwiperSlide>
                      <SwiperSlide>
                      <img
                        className={styles.detailSliderImgBottom}
                        src="https://st.myideasoft.com/shop/du/83/myassets/products/849/20200120-141449.jpg?revision=1587825956"
                      />
                    </SwiperSlide>
                    </Swiper>
                  </div>
                  <div className={styles.promote}>
                    <div className="d-flex align-items-center">
                      <OutlineButton
                        buttonContent="İrəli çək"
                        buttonBorder="1px solid #A96263"
                      />
                      <OutlineButton
                      buttonContent="VİP et"
                      buttonBorder="1px solid #80BC96"
                    />
                    <OutlineButton
                    buttonContent="Premium et"
                    buttonBorder="1px solid #FF8B6A"
                  />
                    </div>
                  </div>
                  <div className={styles.advertPersonAbout}>
                   <AdvertPerson/>
                  </div>
                </div>
              </div>
              <div className="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-xxl-6">
                <div className={styles.rightTop}>
                  <div className={styles.headText}>
                    <div className="d-flex align-items-start justify-content-between">
                      <div className={`${styles.productName}`}>
                        <h1>Uşaq mebel Kombinezon LC Waikiki</h1>
                        <Box
                          sx={{
                            "& > legend": { mt: 2 },
                          }}
                        >
                          <Rating
                            name="simple-controlled"
                            value={value}
                            onChange={(event, newValue) => {
                              setValue(newValue);
                            }}
                          />
                        </Box>
                      </div>
                      <div className={styles.share}>
                        <div className="d-flex align-items-center">
                          <Image className={styles.shareIco} src={shareIco} />
                          <Image className={styles.wishIco} src={wishIco} />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.pricing}>
                    <div className="row  justify-content-between">
                      <div className="col-8 col-sm-6 col-md-4 col-lg-5 col-xl-4 col-xxl-4">
                        <div className={styles.pricingLeft}>
                          <div className="d-flex justify-content-between">
                            <div className={styles.discountPrice}>
                              <p>16 AZN</p>
                            </div>
                            <div className={`${styles.oldPrice} my-2 mx-3`}>
                              <del>20 AZN</del>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-12 col-sm-12 col-md-3 col-lg-5 col-xl-3 col-xxl-3">
                        <div className={styles.discountDegree}>
                          <p>Endirim: 20 %</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.advertDescription}>
                    <ul className={`${styles.descList} m-0 p-0`}>
                      <li>
                        Elanın nömrəsi: <span>81063</span>
                      </li>
                      <li>
                        Elanın tarixi: <span>06.08.2021</span>
                      </li>
                      <li>
                        Baxış sayı: <span>15</span>
                      </li>
                    </ul>
                  </div>
                  <div className={styles.advertTabMenu}>
                    <Box sx={{ width: "100%", typography: "body1" }}>
                      <TabContext value={valueTab}>
                        <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                          <TabList
                            textColor="inherit"
                            indicatorColor="inherit"
                            onChange={handleChange}
                          >
                            <Tab
                              className={`${styles.tabColor}`}
                              label="Haqqında"
                              value="1"
                            />
                            <Tab
                              className={`${styles.tabColor}`}
                              label="Dəyərləndirmə"
                              value="2"
                            />
                            <Tab
                              className={`${styles.tabColor}`}
                              label="Rəylər"
                              value="3"
                            />
                          </TabList>
                        </Box>
                        <TabPanel value="1">
                          <div className={styles.advertAboutText}>
                            <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing
                              elit. Justo faucibus etiam ut tristique elit
                              aliquam, gravida. In laoreet risus, a ac. Ultrices
                              fermentum amet integer non ac tellus. Imperdiet
                              nec volutpat in vitae bibendum imperdiet in.
                            </p>
                            <ul className={styles.advertCategory}>
                              <li>
                                Ölçü: <span>XS</span>
                              </li>
                              <li>
                                Rəng: <span>Qırmızı</span>
                              </li>
                              <li>
                                Şəhər: <span>Bakı</span>
                              </li>
                              <li>
                                Vəziyyət: <span>Yeni</span>
                              </li>
                              <li>
                                Çatdırılma: <span>Var</span>
                              </li>
                            </ul>
                          </div>
                        </TabPanel>
                        <TabPanel value="2">Item Two</TabPanel>
                        <TabPanel value="3">
                          <Disqus.DiscussionEmbed
                            shortname={disqusShortname}
                            config={disqusConfig}
                          />
                        </TabPanel>
                      </TabContext>
                    </Box>
                  </div>
                </div>
              </div>
              <div className="col-12 col-sm-12">
              <div className={styles.advertPersonAboutResponsive}>
              <AdvertPerson/>
             </div>
              </div>
            </div>
            <div className="sameProduct">
            <AdvertItem
            titleText="Bənzər məhsullar"
            textColor="#F0B74C"
            buttonText="Daha çox"
            cardItem={
              
              products
            .filter((p) => p.locale === locale && p.isVip === true)
            .map((fakeApi, i) => {
              return (
                <AdvertCard
               
                id={fakeApi.id}
                 key={i}
                  photoUrl={cardImg}
                  title={fakeApi.productName}
                  price={fakeApi.price}
                  ticket={fakeApi.sellStatus}
                  iconOne={diamond}
                  iconTwo={crystal}
                  date={fakeApi.dateAndCity}
                  href="/ProductDetail"
                  isAddWish = {false}
                  isOffer = {false}
                />
              );
            })
          }
          />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

const mapStateToProps = state => {
  return {
    products: state.cart.products,
  }
}

export default connect (mapStateToProps)(ProductDetail);
