import styles from "../styles/productDetail.module.scss";
import Head from "next/head";

const ProductDetail = () => {
 
  return (
    <>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.productDetail}>
          <div className="container">
            <div className="row align-items-center">
              <div className={styles.leftTop}>
                <div className={styles.sliderDetail}></div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default ProductDetail;
