import Head from "next/head";
import styles from "../styles/searchResult.module.scss";
import Filter from "../components/filter/Filter";
import AdvertCard from "../components/advertSection/AdvertCard";
import cardImg from "../public/assets/image/MaskGroup.png";
import diamond from "../public/assets/image/diamond1.png";
import crystal from "../public/assets/image/jam_crown-f.png";

const SearchResult = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className={styles.headText}>
            <div className="d-flex align-items-center">
              <h1>Axtarış nəticəsi</h1>
              <span className="mx-2">(12 məhsul)</span>
            </div>
          </div>
          <div className={styles.filter}>
            <Filter />
          </div>
          <div className={styles.searchResult}>
            <div className="row align-items-center">
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
              <div className="col-6 col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-3">
                <AdvertCard
                  photoUrl={cardImg}
                  title="Uşaq geyimi Kombinezon LC Waikiki"
                  price="30 Azn"
                  ticket="Mağaza"
                  iconOne={diamond}
                  iconTwo={crystal}
                  date="Bakı, 08-08-2021"
                  href="/ProductDetail"
                  isAddWish={false}
                  isOffer={false}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default SearchResult;
