import Head from "next/head";
import AdvertCard from "../components/advertSection/AdvertCard";
import CategoryList from "../components/categoryItem/CategoryList";
import styles from "../styles/product.module.scss";
import cardImg from "../public/assets/image/MaskGroup.png";
import diamond from "../public/assets/image/diamond1.png";
import crystal from "../public/assets/image/jam_crown-f.png";
import Filter from "../components/filter/Filter";
import * as Icon from "react-bootstrap-icons";
import ShopItem from "../components/advertSection/shopItem";
import shopImg from "../public/assets/image/shopImg.png";

const Product = () => {
  return (
    <div>
      <Head>
        <title>Shop Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.myContainer}>
          <div className="row">
            <div className=" col-xl-2 col-xxl-2">
              <div className={styles.categoryListProduct}>
                <CategoryList />
              </div>
            </div>
            <div className=" col-xl-10 col-xxl-10">
              <div className={styles.allProductList}>
                <div className="headTextProduct">
                  <h1>Magazalar</h1>
                </div>
                <div className="filterList">
                  <Filter />
                </div>
                <div className="productsItems">
                  <div className="row align-items-center">
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                    <ShopItem
                      title="Panda Kids"
                      link="/"
                      advertCount="120"
                      phone="(+994 55) 555-55-55"
                      location="Bakı, Nərimanov rayonu"
                      locationLink="https://goo.gl/maps/VrmZBxuE9vsGidH87"
                      photo={shopImg}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Product;
