import Head from "next/head";
import SiteText from "../components/siteText/SiteText";

const SiteAds = () => {
  return (
    <div>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SiteText
          title="Saytda reklam"
          description="TAP.AZ - Azərbaycanın ən məşhur və stabil artan internet resurslarından biridir. Hər gün bu saytı minlərlə insan ziyarət edir.

          TAP.AZ saytında reklam sizin brendləriniz, məhsullarınız, xidmətləriniz, aksiyalarınız və əhəmiyyətli hadisələriniz barədə məlumatı çox geniş auditoriyaya çatdırmaq üçün ən gözəl üsüllarından biridir!
          
          Siz həm brendinizin tanınmasının əhəmiyyətli dərəcədə artmasına, həm də məhsullarınız barədə məlumatın geniş yayılmasına nail olacaq, və həmçinin şirkətlərinizin internet saytlarının ziyarət edilməsinin sadə üsülla çoxalması imkanını əldə edəcəksiniz.
          
          Sizinlə əməkdaşlığa şad olardıq!
          
          info@digit.az"
          color="#FFF6F4"
          height="500px"
          borderColor="#C87C69"
        />
      </main>
    </div>
  );
};

export default SiteAds;
