import Head from "next/head";
import SiteText from "../components/siteText/SiteText";

const UserAgreement = () => {
  return (
    <div>
      <Head>
        <title>User Agreement Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SiteText
          title="İstifadəçi razılaşması"
          description="1. Ümumi şərtlər
          1.1. Həmin Razılaşma http://tap.az/ Servisin İstifadəçiləri tərəfindən istifadə şərtlərini müəyyən edir.
          
          1.2. Həmin İstifadəçi Razılaşmanın məqsədləri üçün aşağıda göstərilən terminlər və təyinlər aşağıdakı mənada tətbiq olunur:
          
          1.2.1. Servis – İnternet şəbəkəsində http://tap.az/ ünvanında yerləşdirilmiş İnternet-resursu (sayt), müxtəlif əməliyyat sistemləri əsasında sayta əlavələr və başqa xidmətlər, həmçinin proqram təminatıdır, saytın, əlavələrin və başqa xidmətlərin dizaynı (qrafiki tərtibatı), məlumat bazası, xidmətlərin istənilən bölməsi (yarımbölmələri), həmçinin xidmətlərdə Administrasiya və İstifadəçilər tərəfindən yerləşdirilmiş informasiyadır.
          1.2.2. Administrasiya – Servisin inzibatçılığını Azərbaycan Respublikasının qanunvericiliyinə uyğun olaraq yaradılmış və qeydiyyatdan keçmiş “DİGİTAL CLASSİFİEDS” OÜ Şirkətinin Azərbaycan Respublikasındakı Filialı (VÖEN: 1404350071) həyata keçirir. Servisə dair bütün mülkiyyət hüquqları müstəsna olaraq Filiala aiddir.
          1.2.3. İstifadəçi – razılaşma şərtlərini qəbul etmiş və Servis xidmətlərindən istifadə edən istənilən hüquq səlahiyyəti olan şəxsdir.
          1.2.4. Şəxsi kabinet – bu İstifadəçinin mühitinin İstifadəçi tərəfindən müəyyən edilmiş (yerləşdirilmiş) məlumatlar və qurmalar məcmusudur. Hər hansı bir İstifadəçinin yalnız bir Şəxsi kabinetə malik olmaq hüququ var.
          1.2.5. İstifadəçinin şəxsi informasiyası – İstifadəçi haqqında məlumatlardır və ya məlumatlar məcmusudur ki, İstifadəçi özü haqqında, İstifadəçinin şəxsi məlumatları, Servisdən istifadə prosesində Administrasiyaya avtomatik olaraq ötürülən informasiya, o cümlədən IP-ünvan, cookie-dən informasiya, İstifadəçinin brauzeri haqqında və İstifadəçi haqqında başqa informasiyalar daxil olmaqla, qeydiyyat vaxtı sərbəst və ya Servisdən istifadə prosesində təqdim edir.
          1.2.6. İnformasiya – Servisdə İstifadəçi və ya Administrasiya tərəfindən yerləşdirilmiş istənilən informasiyadır.
          1.2.7. Spam – alanlar tərəfindən kütləvi, icazə verilməyən və/və ya gözlənməyən reklam, informasiya, təşviqat və ya başqa xarakterli poçt və başqa göndərilmələrdir.
          1.2.8. Mal – bu məhsul, işlər, xidmətlər, maddi-texniki resurslar, mülki və qeyri-mülki hüquqlardır.
          1.2.9. Həmin Razılaşmanın Tərəfləri – Administrasiya və İstifadəçidir.
          
          1.3. Həmin İstifadəçi Razılaşmasında istifadə olunan və Terminlər və təyinlər bəndində əksini tapmayan istənilən terminlər və anlayışlar, İstifadəçi Razılaşmasının mətnindən yaranan mənaya müvafiq olaraq izah ediləcəkdir. İstifadəçi Razılaşmasında istifadə edilən terminin və ya təyinin izah edilməsi barədə istənilən fikir ayrılıqlarının yaranması halında Administrasiya tərəfindən müəyyən edilən izah etmə tətbiq ediləcəkdir.
          
          1.4. Servis xidmətlərindən və materiallarından istifadə edilmə qüvvədə olan qanunvericiliyin normaları, həmçinin də hazırkı Razılaşma ilə tənzimlənir."
          color="#F8FDFF"
          borderColor="#4085A3"
          height="auto"
        />
      </main>
    </div>
  );
};

export default UserAgreement;
