import Head from "next/head";
import WishCart from "../components/wishCart/WishCart";

const WishList = () => {
  return (
    <div>
      <Head>
        <title>Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WishCart />
      </main>
    </div>
  );
};

export default WishList;
